# Generated by Django 4.2.30 on 2026-05-11 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('images', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
                ('ingredient_quantities', models.TextField()),
                ('ingredients', models.TextField()),
                ('aggregated_rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('fat_content', models.IntegerField()),
                ('saturated_fat_content', models.IntegerField()),
                ('cholesterol_content', models.IntegerField()),
                ('sodium_content', models.IntegerField()),
                ('carbohydrates_content', models.IntegerField()),
                ('fiber_content', models.IntegerField()),
                ('sugar_content', models.IntegerField()),
                ('protein_content', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('recipe_yield', models.IntegerField()),
                ('instructions', models.TextField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
